 ### Importing Libaries

In [366]:
import pandas as pd

### Importing and Viewing the Dataset

In [367]:
df = pd.read_excel(r"E:\DS\Dataset\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

### Dropping the Duplicates

In [368]:
df = df.drop_duplicates()
df
#Note the dataset 21 rows changed to 20 since the duplicate has beend dropped(Anaking Skywalker id Duplicate)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

### Checking the Datatypes of the Dataframe

In [369]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         20 non-null     int64
 1   First_Name         20 non-null     object
 2   Last_Name          19 non-null     object
 3   Phone_Number       18 non-null     object
 4   Address            20 non-null     object
 5   Paying Customer    20 non-null     object
 6   Do_Not_Contact     16 non-null     object
 7   Not_Useful_Column  20 non-null     bool
dtypes: bool(1), int64(1), object(6)
memory usage: 1.3+ KB

### Dropping the Data which isn't useful

In [370]:
df = df.drop(columns="Not_Useful_Column")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

### Stripping the unnecessary characters in Last Name Column

In [371]:
df["Last_Name"]

0         Baggins
1           Nadir
2          /White
3         Schrute
4            Snow
5         Swanson
6          Winger
7          Holmes
8             NaN
9          Parker
10         Gamgee
11      ...Potter
12         Draper
13          Knope
14    Flenderson_
15        Weasley
16          Scott
17           Kent
18         Braton
19      Skywalker
Name: Last_Name, dtype: object

In [372]:
df["Last_Name"] = df["Last_Name"].str.strip('123._/') 
#Notice Index 2,11,14
df["Last_Name"]

0        Baggins
1          Nadir
2          White
3        Schrute
4           Snow
5        Swanson
6         Winger
7         Holmes
8            NaN
9         Parker
10        Gamgee
11        Potter
12        Draper
13         Knope
14    Flenderson
15       Weasley
16         Scott
17          Kent
18        Braton
19     Skywalker
Name: Last_Name, dtype: object

### Replacing the Unneccessary Characters

In [373]:
df['Phone_Number']

0     123-545-5421
1     123/643/9775
2       7066950392
3     123-543-2345
4     876|678|3469
5     304-762-2467
6              NaN
7     876|678|3469
8              N/a
9     123-545-5421
10             NaN
11      7066950392
12    123-543-2345
13    876|678|3469
14    304-762-2467
15    123-545-5421
16    123/643/9775
17      7066950392
18             N/a
19    876|678|3469
Name: Phone_Number, dtype: object

In [374]:
df["Phone_Number"]=df["Phone_Number"].str.replace(r'[^a-zA-Z0-9]', '',regex=True)
df["Phone_Number"]

0     1235455421
1     1236439775
2            NaN
3     1235432345
4     8766783469
5     3047622467
6            NaN
7     8766783469
8             Na
9     1235455421
10           NaN
11           NaN
12    1235432345
13    8766783469
14    3047622467
15    1235455421
16    1236439775
17           NaN
18            Na
19    8766783469
Name: Phone_Number, dtype: object

In [375]:
#Simple_Method
df["Phone_Number"] = df["Phone_Number"].astype(str)
#Alternate_method
#df["Phone_Number"].apply(lambda x: str(x))

In [376]:
df.info()
# If you see below Phone_number still in object In pandas, strings are stored as object dtype — this is the standard behavior.
# If we apply lambda function it will return without error as shown in next cell

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       20 non-null     int64
 1   First_Name       20 non-null     object
 2   Last_Name        19 non-null     object
 3   Phone_Number     20 non-null     object
 4   Address          20 non-null     object
 5   Paying Customer  20 non-null     object
 6   Do_Not_Contact   16 non-null     object
dtypes: int64(1), object(6)
memory usage: 1.2+ KB

In [377]:
df['Phone_Number'] = df['Phone_Number'].apply(lambda x: x[0:3] + '-' + x[3:6] +'-'+ x[6:10])
df['Phone_Number']

0     123-545-5421
1     123-643-9775
2            nan--
3     123-543-2345
4     876-678-3469
5     304-762-2467
6            nan--
7     876-678-3469
8             Na--
9     123-545-5421
10           nan--
11           nan--
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17           nan--
18            Na--
19    876-678-3469
Name: Phone_Number, dtype: object

### Removing Null Values

In [378]:
df.isnull().sum()
#Note that Last Name and Do not Contact has Null Values

CustomerID         0
First_Name         0
Last_Name          1
Phone_Number       0
Address            0
Paying Customer    0
Do_Not_Contact     4
dtype: int64

In [379]:
df = df.fillna('-')
df
#We can fill anything inside the brackets as per our requirement
#Notice only Last_Name Column has the changes not on Phone_Number since nan is on string type

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,nan--,298 Drugs Driveway,N,-
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,-,Na--,123 Middle Earth,Yes,-
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,-
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,-
18,1019,Creed,Braton,Na--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [380]:
#Remember df["column"].str.replace(pattern, replacement) is the format for .replace()
df["Phone_Number"]=df["Phone_Number"].str.replace('Na','-')
df["Phone_Number"]

0     123-545-5421
1     123-643-9775
2            nan--
3     123-543-2345
4     876-678-3469
5     304-762-2467
6            nan--
7     876-678-3469
8              ---
9     123-545-5421
10           nan--
11           nan--
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17           nan--
18             ---
19    876-678-3469
Name: Phone_Number, dtype: object

In [381]:
df["Phone_Number"]=df["Phone_Number"].str.replace('nan','-')
df["Phone_Number"]

0     123-545-5421
1     123-643-9775
2              ---
3     123-543-2345
4     876-678-3469
5     304-762-2467
6              ---
7     876-678-3469
8              ---
9     123-545-5421
10             ---
11             ---
12    123-543-2345
13    876-678-3469
14    304-762-2467
15    123-545-5421
16    123-643-9775
17             ---
18             ---
19    876-678-3469
Name: Phone_Number, dtype: object

### Splitting

In [382]:
#Syntax df["column"].str.split(pat, n=-1, expand=False)
#pat	Delimiter — what to split on (,,  , -, etc.)	\s+ (whitespace)
#n	Max splits — how many splits to do (-1 = all)	-1 (all)
#expand	Return DataFrame? — True creates separate columns	False

In [383]:
df["Address"].str.split(',',expand=True)

                       0              1       2
0         123 Shire Lane          Shire    None
1    93 West Main Street           None    None
2     298 Drugs Driveway           None    None
3       980 Paper Avenue   Pennsylvania   18503
4       123 Dragons Road           None    None
5       768 City Parkway           None    None
6      1209 South Street           None    None
7          98 Clue Drive           None    None
8       123 Middle Earth           None    None
9       25th Main Street       New York    None
10        612 Shire Lane          Shire    None
11  2394 Hogwarts Avenue           None    None
12      2039 Main Street           None    None
13      343 City Parkway           None    None
14         214 HR Avenue           None    None
15  2395 Hogwarts Avenue           None    None
16      121 Paper Avenue   Pennsylvania    None
17       3498 Super Lane           None    None
18                   N/a           None    None
19     910 Tatooine Road       Tatooine    None

In [384]:
df[["Address","State","Zipcode"]]= df["Address"].str.split(',',expand=True)

In [385]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Zipcode
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Yes,No,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,None,None
2,1003,Walter,White,---,298 Drugs Driveway,N,-,None,None
3,1004,Dwight,Schrute,123-543-2345,980 Paper Avenue,Yes,Y,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,None,None
6,1007,Jeff,Winger,---,1209 South Street,No,No,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,None,None
8,1009,Gandalf,-,---,123 Middle Earth,Yes,-,None,None
9,1010,Peter,Parker,123-545-5421,25th Main Street,Yes,No,New York,None
10,1011,Samwise,Gamgee,---,612 Shire Lane,Yes,No,Shire,None
11,1012,Harry,Potter,---,2394 Hogwarts Avenue,Y,-,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,None,None
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Yes,No,Pennsylvania,None
17,1018,Clark,Kent,---,3498 Super Lane,Y,-,None,None
18,1019,Creed,Braton,---,N/a,N/a,Yes,None,None
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Yes,N,Tatooine,None

### Formatting the Yes or NO to Y or N

#### Multiple columns, single replacement
#### df[['col1', 'col2']].replace('old', 'new')

#### Multiple columns, multiple replacements
#### df[['col1', 'col2']].replace({'old1': 'new1', 'old2': 'new2'})

In [386]:
df[["Paying Customer","Do_Not_Contact"]] = df[["Paying Customer","Do_Not_Contact"]].replace('Yes','Y')
df[["Paying Customer","Do_Not_Contact"]]
#Notice that we didnt use str.replace() but.replace() instead because we are working on a Dataframe and not on a string column. 
# If we use str.replace() it will give us an error since it is not a string column but a dataframe.

   Paying Customer Do_Not_Contact
0                Y             No
1               No              Y
2                N              -
3                Y              Y
4                Y             No
5                Y              Y
6               No             No
7                N             No
8                Y              -
9                Y             No
10               Y             No
11               Y              -
12               Y              N
13               Y             No
14               N             No
15              No              N
16               Y             No
17               Y              -
18             N/a              Y
19               Y              N

In [387]:
df[["Paying Customer","Do_Not_Contact"]] = df[["Paying Customer","Do_Not_Contact"]].replace('No','N')
df[["Paying Customer","Do_Not_Contact"]]

   Paying Customer Do_Not_Contact
0                Y              N
1                N              Y
2                N              -
3                Y              Y
4                Y              N
5                Y              Y
6                N              N
7                N              N
8                Y              -
9                Y              N
10               Y              N
11               Y              -
12               Y              N
13               Y              N
14               N              N
15               N              N
16               Y              N
17               Y              -
18             N/a              Y
19               Y              N

In [388]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Zipcode
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,None,None
2,1003,Walter,White,---,298 Drugs Driveway,N,-,None,None
3,1004,Dwight,Schrute,123-543-2345,980 Paper Avenue,Y,Y,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,None,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,None,None
6,1007,Jeff,Winger,---,1209 South Street,N,N,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,None,None
8,1009,Gandalf,-,---,123 Middle Earth,Y,-,None,None
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,New York,None
10,1011,Samwise,Gamgee,---,612 Shire Lane,Y,N,Shire,None
11,1012,Harry,Potter,---,2394 Hogwarts Avenue,Y,-,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,None,None
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,Pennsylvania,None
17,1018,Clark,Kent,---,3498 Super Lane,Y,-,None,None
18,1019,Creed,Braton,---,N/a,N/a,Y,None,None
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,Tatooine,None

In [389]:
df.fillna('-')

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Zipcode
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,Shire,-
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,-,-
2,1003,Walter,White,---,298 Drugs Driveway,N,-,-,-
3,1004,Dwight,Schrute,123-543-2345,980 Paper Avenue,Y,Y,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,-,-
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,-,-
6,1007,Jeff,Winger,---,1209 South Street,N,N,-,-
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,-,-
8,1009,Gandalf,-,---,123 Middle Earth,Y,-,-,-
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,New York,-
10,1011,Samwise,Gamgee,---,612 Shire Lane,Y,N,Shire,-
11,1012,Harry,Potter,---,2394 Hogwarts Avenue,Y,-,-,-
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,-,-
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,-,-
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,-,-
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,-,-
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,Pennsylvania,-
17,1018,Clark,Kent,---,3498 Super Lane,Y,-,-,-
18,1019,Creed,Braton,---,N/a,N/a,Y,-,-
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,Tatooine,-

In [390]:
# Here we do not want to call customer with Do_Not_Contact as Y and Phone_Number  as - since it is not a valid phone number. 
#But if we use dropna() it will drop the entire row which is not what we want.

In [391]:
for x in df.index:
    if df.loc[x, 'Do_Not_Contact'] == 'Y':
        df.drop(x, inplace=True)

In [392]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Zipcode
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,Shire,None
2,1003,Walter,White,---,298 Drugs Driveway,N,-,None,None
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,None,None
6,1007,Jeff,Winger,---,1209 South Street,N,N,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,None,None
8,1009,Gandalf,-,---,123 Middle Earth,Y,-,None,None
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,New York,None
10,1011,Samwise,Gamgee,---,612 Shire Lane,Y,N,Shire,None
11,1012,Harry,Potter,---,2394 Hogwarts Avenue,Y,-,None,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,None,None
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,Pennsylvania,None
17,1018,Clark,Kent,---,3498 Super Lane,Y,-,None,None
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,Tatooine,None

In [393]:
for x in df.index:
    if df.loc[x, 'Phone_Number'] == '---':
        df.drop(x, inplace=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Zipcode
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,Shire,None
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,None,None
9,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,New York,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,None,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,None,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,None,None
16,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,Pennsylvania,None
19,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,Tatooine,None

In [394]:
#Here is the Final Cleaned Dataset whom we can call for the marketing campaign.
df = df.reset_index(drop=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,State,Zipcode
0,1001,Frodo,Baggins,123-545-5421,123 Shire Lane,Y,N,Shire,None
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,None,None
2,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,None,None
3,1010,Peter,Parker,123-545-5421,25th Main Street,Y,N,New York,None
4,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,None,None
5,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,None,None
6,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,None,None
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,None,None
8,1017,Michael,Scott,123-643-9775,121 Paper Avenue,Y,N,Pennsylvania,None
9,1020,Anakin,Skywalker,876-678-3469,910 Tatooine Road,Y,N,Tatooine,None